Remove set but unused variables
Some compilers catch that these are unused:

 tcmalloc/testing/reclaim_test.cc:157:11: error: variable 'iter' set but not used [-Werror,-Wunused-but-set-variable]
   157 |       int iter = 0;
       |           ^
 1 error generated.

Remove them.

PiperOrigin-RevId: 641919386
Change-Id: I49753b1ec892a5db43445958013fb53ed7fb5f43